# Generated by Django 5.2.3 on 2025-06-16 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('size', models.CharField(choices=[('0-20人', '0-20人'), ('20-99人', '20-99人'), ('100-499人', '100-499人'), ('500+人', '500+人')], default='0-20人', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('description', models.JSONField(blank=True, null=True)),
                ('license_period', models.CharField(max_length=20)),
                ('registered_capital', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '企业',
                'verbose_name_plural': '企业',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '行业',
                'verbose_name_plural': '行业',
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('其他', '其他')], default='其他', max_length=5)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('expected_work_type', models.CharField(choices=[('兼职', '兼职'), ('全职', '全职'), ('实习', '实习')], default='全职', max_length=10)),
                ('expected_min_salary', models.PositiveSmallIntegerField()),
                ('expected_max_salary', models.PositiveSmallIntegerField()),
                ('current_status', models.CharField(choices=[('在职', '在职'), ('离职', '离职'), ('应届生', '应届生')], default='离职', max_length=10)),
                ('resume_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('work_experience', models.JSONField(blank=True, null=True)),
                ('education', models.CharField(choices=[('专科', '专科'), ('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=10)),
                ('project_experience', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '求职者',
                'verbose_name_plural': '求职者',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '语言能力',
                'verbose_name_plural': '语言能力',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('985', '985'), ('211', '211'), ('双一流', '双一流'), ('普通', '普通')], default='普通', max_length=10)),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'unique_together': {('name', 'province')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_salary', models.PositiveSmallIntegerField()),
                ('max_salary', models.PositiveSmallIntegerField()),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experience_required', models.CharField(choices=[('不限', '不限'), ('应届生', '应届生'), ('1-3年', '1-3年'), ('3-5年', '3-5年'), ('5年+', '5年+')], max_length=10)),
                ('education_required', models.CharField(choices=[('不限', '不限'), ('专科', '专科'), ('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=10)),
                ('description', models.JSONField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='resume.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.company')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.industry')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.jobtitle')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
            },
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='resume.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.company')),
            ],
            options={
                'verbose_name': '企业_位于_城市',
                'verbose_name_plural': '企业_位于_城市',
                'unique_together': {('company', 'city')},
            },
        ),
        migrations.CreateModel(
            name='DesiredIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.industry')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.jobseeker')),
            ],
            options={
                'verbose_name': '求职者_期望_行业',
                'verbose_name_plural': '求职者_期望_行业',
                'unique_together': {('job_seeker', 'industry')},
            },
        ),
        migrations.CreateModel(
            name='DesiredCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='resume.city')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.jobseeker')),
            ],
            options={
                'verbose_name': '求职者_期望_城市',
                'verbose_name_plural': '求职者_期望_城市',
                'unique_together': {('job_seeker', 'city')},
            },
        ),
        migrations.CreateModel(
            name='CompanyFavoriteJobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_time', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.company')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.jobseeker')),
            ],
            options={
                'verbose_name': '企业用户_收藏_求职者',
                'verbose_name_plural': '企业用户_收藏_求职者',
                'unique_together': {('company', 'job_seeker')},
            },
        ),
        migrations.CreateModel(
            name='DesiredJobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.jobseeker')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.jobtitle')),
            ],
            options={
                'verbose_name': '求职者_期望_职位',
                'verbose_name_plural': '求职者_期望_职位',
                'unique_together': {('job_seeker', 'job_title')},
            },
        ),
        migrations.CreateModel(
            name='JobSeekerLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(max_length=50)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.jobseeker')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.language')),
            ],
            options={
                'verbose_name': '求职者_掌握_语言',
                'verbose_name_plural': '求职者_掌握_语言',
                'unique_together': {('job_seeker', 'language')},
            },
        ),
        migrations.CreateModel(
            name='FavoritePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_time', models.DateTimeField(auto_now_add=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.jobseeker')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.position')),
            ],
            options={
                'verbose_name': '求职者_收藏_岗位',
                'verbose_name_plural': '求职者_收藏_岗位',
                'unique_together': {('job_seeker', 'position')},
            },
        ),
        migrations.CreateModel(
            name='PositionLanguageRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.language')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.position')),
            ],
            options={
                'verbose_name': '岗位_要求_语言',
                'verbose_name_plural': '岗位_要求_语言',
                'unique_together': {('position', 'language')},
            },
        ),
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('专科', '专科'), ('学士', '学士'), ('硕士', '硕士'), ('博士', '博士'), ('MBA', 'MBA'), ('EMBA', 'EMBA')], max_length=10)),
                ('major', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.jobseeker')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='resume.school')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
                'unique_together': {('job_seeker', 'school', 'degree', 'major')},
            },
        ),
        migrations.CreateModel(
            name='CompanyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.company')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.tag')),
            ],
            options={
                'verbose_name': '企业_标签',
                'verbose_name_plural': '企业_标签',
                'unique_together': {('company', 'tag')},
            },
        ),
    ]
